name: todo-app
services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next
    env_file:
      - .env
    networks:
      - todo-app
    ports:
      - "${NEXT_HOST_PORT:-3000}:3000"
    volumes:
      - ${NEXT_SRC_DIR:-.}:/workdir

networks:
  # need to run `docker network create todo-app`
  todo-app:
    external: true
